name: board_front
description: SIT-board

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  dotted_line: ^3.1.0
  flutter:
    sdk: flutter

  flutter_colorpicker: ^1.0.3
  intl: ^0.17.0
  mqtt_client: ^9.7.2
  shared_preferences: ^2.0.15
  board_event_bus: { path: modules/board_event_bus }
  quds_popup_menu: ^0.0.1+1
  vector_math: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
