name: board_front
description: SIT-board

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  dotted_line: ^3.1.0
  flutter:
    sdk: flutter

  flutter_colorpicker: ^1.0.3
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  board_event_bus: { path: modules/board_event_bus }
  json_model_undo_redo: { path: modules/json_model_undo_redo }
  json_model_sync: { path: modules/json_model_sync }
  platform_widget: { path: modules/platform_widget }
  quds_popup_menu: ^0.0.1+1
  vector_math: ^2.1.2
  window_manager: ^0.2.7
  universal_platform: ^1.0.0+1
  flutter_easyloading: ^3.0.5
  file_picker: ^5.2.2
  uuid: ^3.0.6
  flutter_widget_from_html_core: ^0.9.0
  flutter_markdown: ^0.6.13
  flutter_settings_screens: ^0.3.3-null-safety+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
