name: board_front
description: SIT-board

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  interactive_infinity_container: { path: modules/interactive_infinity_container }
  intl: ^0.17.0
  mqtt_client: ^9.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
