name: json_diff_patcher
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  json_field_modifier: { path: ../json_field_modifier }

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
